const product_card = [
  {
    id: 1,
    product_name: "Pro 1",
    description: "2 GB Storage",
    price: "$25000/Year",
    thumb: "6.jpg",
    desc2: "Artifactory Binary Repository ",
    desc3: "Open Source Vulnerability Scanning",
    desc4: "Cloud Provider of Choice",
    desc5: "Artifactory Binary Repository",
  },

  {
    id: 2,
    product_name: "Pro 2",
    description: "4 GB Storage",
    price: "$29000/Year",
    thumb: "7.jpg",
    desc2: "Artifactory Binary Repository ",
    desc3: "Open Source Vulnerability Scanning",
    desc4: "Cloud Provider of Choice",
    desc5: "Artifactory Binary Repository",
  },
  {
    id: 3,
    product_name: "Pro 3",
    description: "8 GB Storage",
    price: "$35000/Year",
    thumb: "8.jpg",
    desc2: "Artifactory Binary Repository ",
    desc3: "Open Source Vulnerability Scanning",
    desc4: "Cloud Provider of Choice",
    desc5: "Artifactory Binary Repository",
  },
  {
    id: 4,
    product_name: "Pro 4",
    description: "16 GB Storage",
    price: "$35000/Year",
    thumb: "10.jpg",
    desc2: "Artifactory Binary Repository ",
    desc3: "Open Source Vulnerability Scanning",
    desc4: "Cloud Provider of Choice",
    desc5: "Artifactory Binary Repository",
  },
  {
    id: 5,
    product_name: "Pro 5",
    description: "32 GB Storage",
    price: "$35000/Year",
    thumb: "cloud-server.png",
    desc2: "Artifactory Binary Repository ",
    desc3: "Open Source Vulnerability Scanning",
    desc4: "Cloud Provider of Choice",
    desc5: "Artifactory Binary Repository",
  },
  {
    id: 6,
    product_name: "pro 6",
    description: "64 GB Storage",
    price: "$35000/Year",
    thumb: "cloud2.jpg",
    desc2: "Artifactory Binary Repository ",
    desc3: "Open Source Vulnerability Scanning",
    desc4: "Cloud Provider of Choice",
    desc5: "Artifactory Binary Repository",
  },
];

export default product_card;
